name: first workflow

on:
  push:
      branches:
        - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print welcome
        run: echo "welcome"
      - name: checkout repo
        uses: actions/checkout@v7.0.1
      - name: show files in the repo
        run: ls -la
        
      
